import Head from 'next/head'
import Image from 'next/image'

import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';


import Container from '@mui/material/Container';

import InputLabel from '@mui/material/InputLabel';
import Grid from '@mui/material/Grid';
import FormControl from '@mui/material/FormControl';
import FormLabel from '@mui/material/FormLabel';
import FormControlLabel from '@mui/material/FormControlLabel';

import Radio from '@mui/material/Radio';
import RadioGroup from '@mui/material/RadioGroup';


import TextField from '@mui/material/TextField';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

import AdapatationReviewCard from '../components/AdaptationReviewCard';
import { useState } from 'react';
import { fetchMovieReviews } from '../api-calls/review-endpoints';

export default function Home() {
  const [reviews, setReviews] = useState([]);
  // Our form info (user input) can be stored into state
  const [title, setTitle] = useState('');
  const [comments, setComments] = useState('');
  const [rating, setRating] = useState(0);
  // Track api call errors
  const [apiError, setApiError] = useState('');

  const handleSubmit = (ev) => {
    ev.preventDefault(); // Intercept the browser's default
    console.log('submitted form');
    // One of the things you will find different from "regular"
    // form submit handlers is that we will NOT be doing any
    // .querySelector() or checking the form's .element to get
    // the inputs.
    // Instead, all of the input controls are directly updating
    // the state of our component through their value={} and
    // onChange={} props.
    fetch('http://localhost:5000/reviews', {
      method: "POST",
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        title: title,  // shorthand is to just say    title,
        comment: comments,
        rating
      })
    }).then((res) => res.json())
    .then(data => {
      // do a console.log to see how the endpoint responds to a POST
      setReviews([data, ...reviews]); // prepend the data to my array
      // Clear the form inputs
      setTitle('');
      setComments('');
      setRating(0);
    })
  }

  const loadAllReviews = () => {
    console.log('loadAllReviews called');
    fetchMovieReviews()
      .then(data => {
        console.log(data);
        setReviews(data);
      })
      .catch(err => {
        // TODO: Handle the thrown errors
        // d'oh!
        console.log(err, typeof err);
        setApiError(err.message);
      });
  }

  return (
    <div>
      <Head>
        <title>Adaptation Reviews.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            Adaptations Reviews
          </Typography>
        </Toolbar>
      </AppBar>
      <main>
        <Container maxWidth="md">
          <form onSubmit={handleSubmit}>
            <Grid container spacing={3}>
              <Grid item xs={12} sm={12}>
                <TextField
                  id="title"
                  name="title"
                  label="Adaptation Title"
                  fullWidth
                  variant="standard"
                  value={title}
                  onChange={ (e) => { setTitle(e.target.value); } }
                />
              </Grid>
              <Grid item xs={12} sm={12}>
                <TextField
                  id="review-comments"
                  name="review-comments"
                  label="Comments"
                  fullWidth
                  variant="standard"
                  value={comments}
                  onChange={ (e) => { setComments(e.target.value); } }
                />
              </Grid>
              <Grid item xs={12} sm={12}>
                <FormControl>
                  <FormLabel id="adaptation-rating">Rating</FormLabel>
                  <RadioGroup
                    row
                    aria-labelledby="adaptation-rating"
                    name="rating-buttons-group"
                    value={rating}
                    onChange={ (ev) => { setRating(ev.target.value); }}
                  >
                    <FormControlLabel value="1" control={<Radio />} label="1" />
                    <FormControlLabel value="2" control={<Radio />} label="2" />
                    <FormControlLabel value="3" control={<Radio />} label="3" />
                    <FormControlLabel value="4" control={<Radio />} label="4" />
                    <FormControlLabel value="5" control={<Radio />} label="5" />
                    <FormControlLabel value="6" control={<Radio />} label="6" />
                    <FormControlLabel value="7" control={<Radio />} label="7" />
                    <FormControlLabel value="8" control={<Radio />} label="8" />
                    <FormControlLabel value="9" control={<Radio />} label="9" />
                    <FormControlLabel value="10" control={<Radio />} label="10" />
                  </RadioGroup>
               </FormControl>
              </Grid>
              <Grid item xs={12} sm={12}>
                <Button
                  variant="contained"
                  type="submit"
                >
                  Add New Review
                </Button>
              </Grid>
            </Grid>
          </form>
          <Box
            sx={{
              pt: 2,
              pb: 2,
            }}
          >
            <Button
              variant="contained"
              onClick={loadAllReviews}
            >
              Load All Current Reviews
            </Button>
          </Box>
          {
            apiError ?
            <Box sx={{pt: 2, pb: 2}}>
              {apiError}
            </Box>
            : ''
          }
          {reviews.map((adaptation, index)=> {
            return <AdapatationReviewCard
                      title={adaptation.title}
                      comment={adaptation.comment}
                      rating={adaptation.rating}
                      key={index}
                   />
          })}

        </Container>
      </main>
    </div>
  )
}
