
import { useEffect, useState } from 'react'


import Head from 'next/head'

import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';

import AgencyCard from '@components/AgencyCard';
import NavBar from '@components/NavBar';

import { getAgencies } from '@utils/api/agencies'

// NOTE: The name `getServerSideProps` is very specific;
//       You must use that name if you want SSR via NextJS.
export async function getServerSideProps(context) {
  console.log('This message should only appear on the server, NOT in the browser.');
  const agencies = await getAgencies();
  return {
    props: {
      agenciesData: agencies.results
    }, // will be passed to the page component as props
  }
}

export default function Home(props) {
  // console.log('Home props:', props);
  const { agenciesData } = props;
  // const [agenciesData, setAgenciesData] = useState([])
  
  // useEffect(()=> {
  //   // fire this on load.
  //   getAgencies().then((data)=> {
  //     console.log(data)
  //     setAgenciesData(data.results)
  //   })
  // }, [])


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <NavBar />

        <Container sx={{paddingTop:2}} component="main" maxWidth="xs">

          <Typography variant="h3">
            Space Agencies
          </Typography>
          <Box
            sx={{
              marginTop: 2,
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
            }}
          >
            {agenciesData.map((agency)=> {
              return <AgencyCard
                key={agency.id}
                id={agency.id}
                imageUrl={agency.image_url}
                name={agency.name}
                abbreviation={agency.abbrev}
                description={agency.description}
              />
            })}

          </Box>
        </Container>

    </div>
  )
}
